[project]
name = 'psychic_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.file_tag_moderation]
path = 'contracts/file_tag_moderation.clar'
clarity_version = 2
epoch = 2.5

[contracts.value_locking]
path = 'contracts/value_locking.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote_audit_trail]
path = 'contracts/vote_audit_trail.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
